version: 2

# This can persist/cache Up across jobs
#  install_up:
#    <<: *container_config
#    steps:
#      - run:
#          name: install-up-runtime
#          command: |
#            curl -sf https://up.apex.sh/install | bash -s -- -b ~/up_bin
#            ~/up_bin/up -v upgrade
#      - save_cache:
#          key: v1-bin-{{ .Environment.CIRCLE_SHA1 }}
#          paths:
#            - ~/up_bin

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10-browsers

git_restore_cache: &git_restore_cache
  restore_cache:
    keys:
      - source-v1-{{ .Branch }}-{{ .Revision }}
      - source-v1-{{ .Branch }}-
      - source-v1-

git_save_cache: &git_save_cache
  save_cache:
    key: source-v1-{{ .Branch }}-{{ .Revision }}
    paths:
      - ".git"


prep_deploy: &prep_deploy
  run:
    name: Prep deploy
    command: |
      sudo chown -R $(whoami) /usr/local/bin
      # Install Up
      curl -sf https://up.apex.sh/install | sh
      # Upgrade Up
      up upgrade


jobs:
  install_and_test_and_build:
    <<: *defaults
    steps:
      - *git_restore_cache
      - checkout
      - *git_save_cache
      - run:
          name: npm install
          command: npm ci --only=prod
      - run:
          name: npm test
          command: npm test
      - run:
          name: Build locations and components
          command: npm run build
      - persist_to_workspace:
          root: ~/repo
          paths:
            - node_modules
            - public/build
  deploy_up_production:
    <<: *defaults
    steps:
      - *git_restore_cache
      - checkout
      - *git_save_cache
      - attach_workspace:
          at: ~/repo
      - *prep_deploy
      - run:
          name: Deploy to Up
          command: up --format=plain deploy production
  deploy_up_staging:
    <<: *defaults
    steps:
      - *git_restore_cache
      - checkout
      - *git_save_cache
      - attach_workspace:
          at: ~/repo
      - *prep_deploy
      - run:
          name: Deploy to Up
          command: up --format=plain deploy staging

workflows:
  version: 2
  install_and_test_and_deploy:
    jobs:
      - install_and_test_and_build
      - deploy_up_production:
          context: apex-up
          requires:
            - install_and_test_and_build
          filters:
            branches:
              only: master
      - deploy_up_staging:
          context: apex-up
          requires:
            - install_and_test_and_build
          filters:
            branches:
              only: staging
